### ISSUE TITLE
Passing a variable from one component to another

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/weddingsbyjosie#1]
Hi @jimafisk
I hope you don't mind me adding you to this repo 😸 

I have being working on the new Plenti site for a friend (as an update from the original Wordpress site I put together for her some years ago) and wanted to ask how I can pass a variable from one component to another.  I got stuck and wasn't sure how to do it.

It's a little complex to explain but I will try. I have a ```service``` content page that imports a number of components in and these components are loaded into the page when clicking on each nav element (one component for each). This all works fine however by default no component content is loaded of course because there is not click event initially to load any. 

One way I thought I could get the first component loaded by default was when a user clicks on the ```Service``` link in the nav of the ```header``` component.  But to do this, I think I need to set a variable that captures the click event, then exports that variable and is then used to trigger the loading of that component. 

The code I tried is as follows :
In the ```header.svelte``` file, I added the ```on:click``` event and save the value in ```selectService```:

```svelte
 <a on:click={() => selectService} href="service">Service</a>
```

Then export this variable: 

```javascript
export let selectService;
```

In the ```service.svelte``` component, I added the same variable and set it to another variable and reassigned it to equal the first component with ```step1```. as follows:

```javascript
selectService = initialService;
let initialService = "step1";
```

Then in the template, I used the or  ```||``` operator to check for the variable something like this:
```svelte
  {#if "step1" === initialService ||  "step1" === selectedStep}

```
From memory the error I got was something about can't read before initialising ....
Please have a look when you can.

Best regards,
Ben

**Comment by jimafisk** [comment]
Hey @jamestagal,

So you just want to load the initial step instead of having the page blank right? I just pushed an update that simply sets the `selectedStep` to `"step1"` when the page initially loads. Does something like that work?

**Comment by jamestagal** [comment]
Hi @jimafisk 

Thanks.. that was easy! yes that is exactly what I was wanting to do.. and such a simple solution too to set it to '''step1''' 😳. that's a relief because my convoluted approach was completely unnecessary 😁

Thanks again.

**Comment by jimafisk** [comment]
Np! Sometimes the simple solution is hidden in the details :blush:. Glad it worked!
