### ISSUE TITLE
Issue with "Steps" in components after moving and cleaning up files

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/weddingsbyjosie#2]
Hi @jimafisk 

I found a bug with the ```service_steps``` components not being able to click through each one as expected. They can be found on the [Service](https://jamestagal.github.io/weddingsbyjosie/service) page. (This deployed version doesn't have this issue) Though I wasn't able to learn how any of the change I did could have caused it.  But then nothing is very obvious when cleaning up and unknowingly causes issues 😸 (Unfortunately, this website template I bought has a lot of JS files which I am not using and external libraries which is very annoying to work with)

Luckily, I hadn't pushed these commits and was able to restore it back to the main/origin and then committed these un-commits to a separate [Bugfix branch](https://github.com/jamestagal/weddingsbyjosie/commits/Bugfix-steps) So if you serve this branch locally and look at the [Service](http://localhost:3000/weddingsbyjosie/service) page and you click on any of the ```Steps``` it doesn't load them.

When you get a change, could you please have a look at a possible cause?

BTW. It probably isn't critical if I just disregard this branch because the ```Steps``` on the ```Service``` page of the main branch & origin/gh-pages is working just fine.

Regards,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

I pulled down the `Bugfix-steps` branch and did a fresh build and the "Steps" seem to work fine for me. What specifically are you seeing? Are there any console errors in the browser?

Can you try looking at it in an incognito / private browsing window to make sure it's not a caching issue?

**Comment by jamestagal** [comment]
Hi Jim,
thanks for taking a look. 
Yeah I don't know...!!! I switched to this Bugfix-steps branch locally, cleared my cache and didn't have any issues navigating through the steps this time!! So beats me! See short screencast below. What was happening was each time I clicked on any step, that step didn't load and it would shoot me up to the top of the screen.  

https://github.com/jamestagal/weddingsbyjosie/assets/6309595/9c7179b7-0cb0-4986-93c4-2d052fac8822



In the screencast you can see all the errors in the console which are the JS files which I'm not using...so I think I will just delete them all :)

Thanks Jim. 
P.S. I'll set the site up on GitLab today and then try adding a custom url. I'll let you know how I go. 😄 Thanks for all your help.

Cheers,
Ben
